### ISSUE TITLE
[wildcards/scan_model] Add root item option for YAML output

### ISSUE THREAD

**Issue by yak1ex** [yak1ex/misc-genai#11]
For each YAML output option, enable to specify root item
--list-root, --variant-root, --singular-root

```yaml
root:
  sd15:
# snip.
  sdxl:
# snip.
```
