### ISSUE TITLE
[wildcards/scan_model] Add entries for auto dispatch by basemodel

### ISSUE THREAD

**Issue by yak1ex** [yak1ex/misc-genai#18]
```yaml
name:
  auto: prefix/name/${base}
  pony: ...
  ilxl: ...
```

prefix should be enable to specify
